apiVersion: v1
kind: Pod
metadata:
  name: test1
spec:
  os: { name: linux }
  nodeSelector:
    kubernetes.io/os: linux
  containers:
  - name: my-app
    image: 10.129.27.120:5000/my_app
    ports:
    - containerPort: 80        
    resources:
      limits:
        cpu: "0.5"
        memory: "512Mi"
    command: ["python3", "src/main.py", "9376"]
