apiVersion: v1
kind: Pod
metadata:
  name: test4
spec:
  os: { name: linux }
  nodeSelector:
    kubernetes.io/os: linux
  containers:
  - name: test
    image: ubuntu:latest
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: "1"
        memory: "1Gi"
      requests:
        cpu: "0.5"
        memory: "512Mi"
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "sleep infinity" ]